server:
  port: 8082

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: demo
          uri: http://localhost:8081
          predicates:
          - Path=/*
          filters:
          # StripPrefix=1表示二级url路径转发
#          - StripPrefix=1
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 2
              key-resolver: '#{@ipKeyResolver}'
#  redis:
                ##    host: 120.55.181.95
                ##    port: 6379
              ##    password: lgj20170417
              ##    database: 12