@startuml
actor 用户 order 1
participant 支付服务 order 2
participant 定时任务 order 3
participant 招行前置机 order 4
participant 招行服务 order 5
participant 结算服务 order 6


用户 -> 支付服务: 开通记账子单元
支付服务 -> 招行服务:  开通记账子单元
用户 -> 招行服务: 银行转账（向记账子单元转账）
用户 <-- 招行服务: 返回转账回执单

定时任务 -> 招行前置机: 每10分钟查询一次流水
招行前置机 -> 招行服务: 查询流水
招行前置机 <-- 招行服务: 返回流水
招行前置机 --> 定时任务: 返回记账子单元资金流水（当日/历史）
定时任务 -> 定时任务: 判断流水是否存在
group 流水不存在
定时任务 -> 定时任务: 打印日志、记录流水
定时任务 -> 结算服务: 发送mq通知到结算服务/3.0服务
结算服务 -> 结算服务: 接收充值mq消息\n保存充值流水、自动走支付流程
end
group 流水存在
定时任务 -> 定时任务: 打印日志、忽略
end

@enduml