@startuml
操作 -> 收款单: 新建-草稿
收款单 -> 收款单: 生成收款单、收款信息（批量）、收款单与出库单关系（批量）

操作 -> 收款单: 编辑
收款单 -> 收款单: 修改收款单、收款信息（批量）、收款单与出库单关系（批量）


操作 -> 收款单: 提交
group 新增
收款单 -> 收款单: 生成收款单、收款信息（批量）、收款单与出库单关系（批量）
end

group 直接提交/修改后提交
收款单 -> 收款单: 修改-->修改以上信息
end

收款单 -> 出库单: 批量更新出库单已/未收金额、收款状态
收款单 -> 应收: 更新应收汇总、新增应收明细

操作 -> 收款单: 撤销/删除
收款单 -> 收款单: 修改收款单审批状态
group 审批已通过
收款单 -> 出库单: 批量反向更新出库单已/未收金额、收款状态
收款单 -> 应收: 减去应收汇总、删除应收明细
end

操作 -> 收款单: 对账
收款单 -> 收款单: 修改收款单对账状态

@enduml