@startuml
AbstractApplicationContext -> AbstractApplicationContext: obtainFreshBeanFactory()
AbstractApplicationContext -> AbstractApplicationContext: invokeBeanFactoryPostProcessors(beanFactory)
AbstractApplicationContext -> PostProcessorRegistrationDelegate: invokeBeanFactoryPostProcessors(beanFactory, getBeanFactoryPostProcessors());

@enduml